#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
step7_compute_xi.py — 统计船位预测误差 ξ_{h,c} 的矩信息。

正式数据契约：
  1. 预测器为无未来泄漏的恒速航位推算(CV)：只使用 t≤t0 的位置估计速度；
  2. 默认统计时长为 5,10,...,60 分钟，与正式决策支持区间一致；
  3. 原始样本按每条源轨迹分别进行 purged train/validation/test 时间切分；
  4. 正式矩只由 train 估计；
  5. 每个 (h,c) 格必须满足最小样本量。默认只允许“低速/动力定位”按预先固定规则合并，
     直航与转弯不跨状态合并；合并后仍不足的格不会写入正式矩文件；
  6. 输出 CSV 中的每一行均为可供正式模型读取的有效格，拒绝格只写入报告。

输出：
  xi_moments_caseB.csv/json     通过样本门槛的 Xi 矩信息；
  _xi_report.txt                数据范围、切分、合并与拒绝记录；
  可选 --dump-samples           输出 purged train/validation/test/all Xi 样本；
  可选 --weather-csv            在同一切分上同步生成 weather_moments_caseB.csv/json、
                                xi_weather_samples_* 与 _weather_residual_report.txt。
"""
from __future__ import annotations

import argparse
import hashlib
import json
import logging
import math
from fractions import Fraction
import sys
from pathlib import Path

import numpy as np
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("xi")

R_EARTH = 6_371_000.0
KN = 0.514444
DEFAULT_HORIZONS_MIN = list(range(5, 61, 5))
STATES = ["直航", "转弯", "低速", "动力定位"]
LOW_SPEED_PAIR = ("低速", "动力定位")
PREDICTOR_NAME = "cv_noleak"
PREDICTOR_CONTRACT = "cv_noleak_backward_window_epoch_seconds"
TIMESTAMP_EPOCH_CONTRACT = "utc_datetime64_ns_to_epoch_seconds"

# Real-history no-leak weather residual contract.  Weather uncertainty is derived
# from the same purged train/validation/test time protocol as Xi; no synthetic or
# adjacent-difference proxy is generated by this step.
WEATHER_PREDICTOR = "weather_speed_primary_coherent_noleak"
WEATHER_PREDICTOR_CONTRACT = "weather_backward_linear_speed_primary_coherent_epoch_seconds_v2"
WEATHER_TIMESTAMP_EPOCH_CONTRACT = TIMESTAMP_EPOCH_CONTRACT
WEATHER_DATA_CONTRACT = "real-history-noleak-weather-residuals-global-weather-nonoverlap-v3-coherent-wind"
WEATHER_TRUTH_CONTRACT = "era5-reanalysis-wind+cmems-historical-wave-hourly-linear-truth-v1"


def _norm(c):
    return "".join(ch for ch in str(c).strip().lower() if ch.isalnum())


def find_col(columns, cands):
    norm = {_norm(c): c for c in columns}
    for cand in cands:
        if _norm(cand) in norm:
            return norm[_norm(cand)]
    # Substring fallback is allowed only for descriptive aliases.  A one-character
    # candidate such as ``t`` would otherwise match ``latitude`` before the true time column.
    for cand in cands:
        key = _norm(cand)
        if len(key) < 3:
            continue
        for c in columns:
            if key in _norm(c):
                return c
    return None


def parse_horizons(text: str) -> list[int]:
    vals = sorted({int(x.strip()) for x in str(text).split(",") if x.strip()})
    if not vals or any(h <= 0 for h in vals):
        raise ValueError("--horizons 必须是逗号分隔的正整数分钟。")
    return vals


def load_track(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    cols = list(df.columns)
    tc = find_col(cols, ["t", "timestamp", "datetime"])
    la = find_col(cols, ["lat", "latitude"])
    lo = find_col(cols, ["lon", "longitude", "lng"])
    sog = find_col(cols, ["sog", "speed", "speedoverground"])
    cog = find_col(cols, ["cog", "course", "courseoverground"])
    if not (tc and la and lo):
        raise ValueError(f"{path.name} 缺 t/lat/lon 列。现有:{cols}")
    out = pd.DataFrame()
    out["t"] = pd.to_datetime(df[tc], errors="coerce", utc=True)
    if out["t"].isna().mean() > 0.5:
        out["t"] = pd.to_datetime(df[tc], dayfirst=True, errors="coerce", utc=True)
    out["lat"] = pd.to_numeric(df[la], errors="coerce")
    out["lon"] = pd.to_numeric(df[lo], errors="coerce")
    out["sog"] = pd.to_numeric(df[sog], errors="coerce") if sog else np.nan
    out["cog"] = pd.to_numeric(df[cog], errors="coerce") if cog else np.nan
    out = out.dropna(subset=["t", "lat", "lon"]).sort_values("t").drop_duplicates("t")
    return out.reset_index(drop=True)


def to_epoch_seconds_utc(values) -> np.ndarray:
    """Convert UTC datetimes to POSIX seconds without assuming pandas storage resolution.

    Pandas 3 may store timezone-aware datetimes at microsecond resolution.  Dividing
    ``astype("int64")`` by ``1e9`` then shrinks epoch seconds by 1000 and silently
    compresses months of AIS history into hours.  Force ``datetime64[ns]`` first.
    """
    ts = pd.to_datetime(values, errors="coerce", utc=True)
    idx = pd.DatetimeIndex(ts)
    naive_utc = idx.tz_convert("UTC").tz_localize(None)
    arr_ns = naive_utc.to_numpy(dtype="datetime64[ns]").astype("int64")
    out = arr_ns.astype(float) / 1e9
    out[arr_ns == np.iinfo(np.int64).min] = np.nan
    return out


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _strict_bool_series(s: pd.Series, name: str) -> np.ndarray:
    vals = []
    for raw in s.tolist():
        if isinstance(raw, (bool, np.bool_)):
            vals.append(bool(raw)); continue
        x = str(raw).strip().lower()
        if x == "true": vals.append(True)
        elif x == "false": vals.append(False)
        else: raise ValueError(f"{name} contains non-boolean value {raw!r}")
    return np.asarray(vals, dtype=bool)


def _wind_vec(speed: np.ndarray, direction_from_deg: np.ndarray) -> np.ndarray:
    to = np.deg2rad((np.asarray(direction_from_deg, float) + 180.0) % 360.0)
    sp = np.asarray(speed, float)
    return np.column_stack([sp * np.sin(to), sp * np.cos(to)])


def _load_weather(path: Path):
    df = pd.read_csv(path)
    need = {"time", "wind10_ms", "wind_dir_from_deg", "Hs_m"}
    miss = need - set(df.columns)
    if miss:
        raise ValueError(f"weather CSV missing columns {sorted(miss)}")
    ts = pd.to_datetime(df["time"], utc=True, errors="coerce")
    if ts.isna().any():
        raise ValueError("weather CSV contains invalid time")
    sec = to_epoch_seconds_utc(ts)
    if len(sec) < 3 or np.any(np.diff(sec) <= 0):
        raise ValueError("weather time must be strictly increasing and unique")
    wind10 = pd.to_numeric(df["wind10_ms"], errors="coerce").to_numpy(float)
    wdir = pd.to_numeric(df["wind_dir_from_deg"], errors="coerce").to_numpy(float)
    hs = pd.to_numeric(df["Hs_m"], errors="coerce").to_numpy(float)
    good = np.isfinite(wind10) & np.isfinite(wdir) & np.isfinite(hs)
    if not bool(good.all()):
        bad = int((~good).sum())
        raise ValueError(f"weather CSV contains {bad} rows with missing wind/Hs; formal residual generation refuses gaps")
    vec = _wind_vec(wind10, wdir)
    return df, sec.astype(float), vec, wind10, hs


def _validate_xi_split(path: Path, expected_split: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    need = {"h_min", "t0_epoch", "t1_epoch", "split", "predictor", "predictor_contract",
            "timestamp_epoch_contract", "sample_overlap_policy", "purge_min",
            "moments_source", "valid_for_formal"}
    miss = need - set(df.columns)
    if miss:
        raise ValueError(f"{path.name} missing formal Xi columns {sorted(miss)}")
    if set(df["split"].dropna().astype(str)) != {expected_split}:
        raise ValueError(f"{path.name} split must be exactly {expected_split!r}")
    if set(df["predictor"].dropna().astype(str)) != {PREDICTOR_NAME}:
        raise ValueError(f"{path.name} Xi predictor mismatch")
    if set(df["predictor_contract"].dropna().astype(str)) != {PREDICTOR_CONTRACT}:
        raise ValueError(f"{path.name} Xi predictor contract mismatch")
    if set(df["timestamp_epoch_contract"].dropna().astype(str)) != {TIMESTAMP_EPOCH_CONTRACT}:
        raise ValueError(f"{path.name} timestamp epoch contract mismatch")
    if set(df["sample_overlap_policy"].dropna().astype(str)) != {"nonoverlap"}:
        raise ValueError(f"{path.name} must come from sample_overlap_policy=nonoverlap")
    if set(df["moments_source"].dropna().astype(str)) != {"train"}:
        raise ValueError(f"{path.name} moments_source must be train")
    if not _strict_bool_series(df["valid_for_formal"], "valid_for_formal").all():
        raise ValueError(f"{path.name} contains valid_for_formal=False")
    for c in ("h_min", "t0_epoch", "t1_epoch", "purge_min"):
        df[c] = pd.to_numeric(df[c], errors="raise")
    hs = sorted(set(float(x) for x in df["h_min"]))
    allowed = [float(x) for x in DEFAULT_HORIZONS_MIN]
    for h in hs:
        if not any(float(h).hex() == a.hex() for a in allowed):
            raise ValueError(f"{path.name} contains off-grid h_min={h!r}")
    max_h = max(hs)
    if float(df["purge_min"].min()) < max_h:
        raise ValueError(f"{path.name} purge_min smaller than max horizon")
    return df


def _truth_interp(t: float, times: np.ndarray, vals: np.ndarray, max_gap_s: float):
    k = int(np.searchsorted(times, t, side="left"))
    if k < len(times) and times[k] == t:
        return np.asarray(vals[k], float)
    if k <= 0 or k >= len(times):
        return None
    t0, t1 = float(times[k-1]), float(times[k])
    if t1 - t0 > max_gap_s:
        return None
    a = (float(t) - t0) / (t1 - t0)
    return (1.0-a) * np.asarray(vals[k-1], float) + a * np.asarray(vals[k], float)


def _forecast_backward_linear(t0: float, t1: float, times: np.ndarray,
                              vals: np.ndarray, max_gap_s: float):
    # last weather observation at or before t0; everything after t0 is forbidden here.
    j = int(np.searchsorted(times, t0, side="right")) - 1
    if j < 1:
        return None, None
    ta, tb = float(times[j-1]), float(times[j])
    if tb > t0 or tb - ta <= 0.0 or tb - ta > max_gap_s:
        return None, None
    slope = (np.asarray(vals[j], float) - np.asarray(vals[j-1], float)) / (tb - ta)
    pred = np.asarray(vals[j], float) + slope * (float(t1) - tb)
    return pred, tb


def _forecast_weather_coherent(t0: float, t1: float, times: np.ndarray,
                               wind_vec: np.ndarray, wind_speed: np.ndarray,
                               hs: np.ndarray, max_gap_s: float):
    """Causal, physically coherent weather forecast used by both Step7 and Step13.

    The scalar wind-speed extrapolation is retained because train-only diagnostics
    show it is slightly more accurate than ``||forecast(vector)||``.  The forecast
    is then projected onto the physical support ``speed >= 0`` and the independently
    extrapolated vector contributes *direction only*.  This guarantees the formal
    invariant ``forecast_speed == ||forecast_vector||`` while preserving the
    no-future-information contract.

    A positive speed with a numerically degenerate predicted direction is rejected
    fail-closed rather than assigned an arbitrary direction.  Negative significant
    wave-height forecasts are likewise rejected rather than silently clipped.
    """
    pvec_raw, obs_v = _forecast_backward_linear(
        t0, t1, times, wind_vec, max_gap_s)
    pspd_raw, obs_s = _forecast_backward_linear(
        t0, t1, times, wind_speed, max_gap_s)
    phs_raw, obs_h = _forecast_backward_linear(
        t0, t1, times, hs, max_gap_s)
    if pvec_raw is None or pspd_raw is None or phs_raw is None:
        return None, "no_history"

    pvec_raw = np.asarray(pvec_raw, float).reshape(2)
    pspd_raw = float(np.asarray(pspd_raw))
    phs = float(np.asarray(phs_raw))
    vals = np.r_[pvec_raw, pspd_raw, phs]
    if not np.all(np.isfinite(vals)):
        return None, "nonfinite"

    # Speed is a magnitude.  Projecting the independently extrapolated scalar onto
    # [0,+inf) is part of the declared predictor, not a route-time ad-hoc repair.
    pspd = max(0.0, pspd_raw)
    raw_norm = float(np.linalg.norm(pvec_raw))
    eps_dir = 1e-12
    if pspd <= eps_dir:
        pvec = np.zeros(2, dtype=float)
        pspd = 0.0
    elif raw_norm <= eps_dir:
        return None, "degenerate_wind_direction"
    else:
        pvec = pvec_raw * (pspd / raw_norm)

    if phs < 0.0:
        return None, "negative_hs"

    coherence = abs(float(np.linalg.norm(pvec)) - float(pspd))
    if coherence > 1e-10 * max(1.0, float(pspd)):
        return None, "wind_coherence_failure"

    return dict(
        wind_vec=np.asarray(pvec, float),
        wind_speed=float(pspd),
        Hs=float(phs),
        observation_epoch=float(max(float(obs_v), float(obs_s), float(obs_h))),
        wind_vector_observation_epoch=float(obs_v),
        wind_speed_observation_epoch=float(obs_s),
        hs_observation_epoch=float(obs_h),
        raw_wind_speed_forecast=float(pspd_raw),
    ), None


def _make_residuals(xi: pd.DataFrame, weather_times: np.ndarray,
                    wind_vec: np.ndarray, wind_speed: np.ndarray, hs: np.ndarray,
                    max_gap_s: float, weather_source_sha256: str,
                    weather_train_source_sha256: str):
    out_rows = []
    dropped = {"no_history": 0, "no_truth": 0, "nonfinite": 0,
               "degenerate_wind_direction": 0, "negative_hs": 0,
               "wind_coherence_failure": 0}
    for row in xi.itertuples(index=False):
        t0 = float(getattr(row, "t0_epoch")); t1 = float(getattr(row, "t1_epoch"))
        fc, reason = _forecast_weather_coherent(
            t0, t1, weather_times, wind_vec, wind_speed, hs, max_gap_s)
        if fc is None:
            dropped[reason] = int(dropped.get(reason, 0)) + 1
            continue
        pvec = np.asarray(fc["wind_vec"], float).reshape(2)
        pspd = float(fc["wind_speed"])
        phs = float(fc["Hs"])
        obs_t = float(fc["observation_epoch"])
        tvec = _truth_interp(t1, weather_times, wind_vec, max_gap_s)
        tspd = _truth_interp(t1, weather_times, wind_speed, max_gap_s)
        ths = _truth_interp(t1, weather_times, hs, max_gap_s)
        if tvec is None or tspd is None or ths is None:
            dropped["no_truth"] += 1; continue
        tvec = np.asarray(tvec, float).reshape(2)
        tspd = float(np.asarray(tspd)); ths = float(np.asarray(ths))
        vals = np.r_[pvec, tvec, pspd, tspd, phs, ths]
        if not np.all(np.isfinite(vals)):
            dropped["nonfinite"] += 1; continue
        d = row._asdict()
        d.update(
            weather_predictor=WEATHER_PREDICTOR,
            weather_predictor_contract=WEATHER_PREDICTOR_CONTRACT,
            weather_timestamp_epoch_contract=WEATHER_TIMESTAMP_EPOCH_CONTRACT,
            weather_truth_contract=WEATHER_TRUTH_CONTRACT,
            weather_data_contract=WEATHER_DATA_CONTRACT,
            weather_observation_epoch=float(obs_t),
            forecast_wind_e_ms=float(pvec[0]), forecast_wind_n_ms=float(pvec[1]),
            truth_wind_e_ms=float(tvec[0]), truth_wind_n_ms=float(tvec[1]),
            wind_error_e_ms=float(tvec[0]-pvec[0]), wind_error_n_ms=float(tvec[1]-pvec[1]),
            forecast_wind_speed_ms=pspd, truth_wind_speed_ms=tspd,
            wind_speed_error_ms=float(tspd-pspd),
            forecast_Hs_m=phs, truth_Hs_m=ths, hs_error_m=float(ths-phs),
            weather_valid_for_formal=True,
            weather_source_sha256=str(weather_source_sha256),
            weather_train_source_sha256=str(weather_train_source_sha256),
        )
        out_rows.append(d)
    return pd.DataFrame(out_rows), dropped




def _binary64_psd_fix2(cov: np.ndarray) -> np.ndarray:
    """Roundoff-only repair so serialized binary64 covariance is exactly PSD-as-real."""
    from fractions import Fraction
    c = np.asarray(cov, float).copy()
    c = 0.5 * (c + c.T)
    if not np.all(np.isfinite(c)):
        raise ValueError("non-finite weather covariance")
    c[0,0] = max(float(c[0,0]), 0.0); c[1,1] = max(float(c[1,1]), 0.0)
    for _ in range(64):
        a = Fraction.from_float(float(c[0,0])); b = Fraction.from_float(float(c[0,1])); d = Fraction.from_float(float(c[1,1]))
        if a >= 0 and d >= 0 and a*d - b*b >= 0:
            return c
        # increase both variances by one ULP; never reduce uncertainty.
        c[0,0] = np.nextafter(float(c[0,0]), math.inf)
        c[1,1] = np.nextafter(float(c[1,1]), math.inf)
    raise RuntimeError("unable to canonicalize 2x2 weather covariance to exact binary64 PSD")

def _make_weather_timeline_train_residuals(weather_times: np.ndarray,
                                           wind_vec: np.ndarray, wind_speed: np.ndarray, hs: np.ndarray,
                                           horizons, train_start_epoch: float, train_end_epoch: float,
                                           purge_min: float, max_gap_s: float) -> tuple[pd.DataFrame, dict]:
    """Build train weather residuals from the weather timeline itself.

    The weather ambiguity must not be weighted by the number of vessels or AIS rows.
    For each horizon, candidates are weather observation times inside the globally safe
    train window.  Accepted intervals [t0,t0+h) are globally non-overlapping for that
    horizon.  Forecasts only use records at or before t0; future records are truth only.
    """
    rows = []
    stats = {}
    for h_raw in sorted(set(float(x) for x in horizons)):
        h = float(h_raw); h_s = 60.0 * h
        last_t1 = -math.inf
        st = {"candidate": 0, "overlap": 0, "no_history": 0, "no_truth": 0,
              "nonfinite": 0, "degenerate_wind_direction": 0, "negative_hs": 0,
              "wind_coherence_failure": 0, "output": 0}
        for t0_raw in weather_times:
            t0 = float(t0_raw)
            if t0 < float(train_start_epoch) or t0 >= float(train_end_epoch):
                continue
            t1 = t0 + h_s
            if t1 > float(train_end_epoch):
                continue
            st["candidate"] += 1
            if t0 < last_t1:
                st["overlap"] += 1
                continue
            fc, reason = _forecast_weather_coherent(
                t0, t1, weather_times, wind_vec, wind_speed, hs, max_gap_s)
            if fc is None:
                st[reason] = int(st.get(reason, 0)) + 1
                continue
            pvec = np.asarray(fc["wind_vec"], float).reshape(2)
            pspd = float(fc["wind_speed"])
            phs = float(fc["Hs"])
            obs_t = float(fc["observation_epoch"])
            tvec = _truth_interp(t1, weather_times, wind_vec, max_gap_s)
            tspd = _truth_interp(t1, weather_times, wind_speed, max_gap_s)
            ths = _truth_interp(t1, weather_times, hs, max_gap_s)
            if tvec is None or tspd is None or ths is None:
                st["no_truth"] += 1
                continue
            tvec = np.asarray(tvec, float).reshape(2)
            tspd = float(np.asarray(tspd)); ths = float(np.asarray(ths))
            vals = np.r_[pvec, tvec, pspd, tspd, phs, ths]
            if not np.all(np.isfinite(vals)):
                st["nonfinite"] += 1
                continue
            rows.append(dict(
                h_min=h, t0_epoch=t0, t1_epoch=t1, purge_min=float(purge_min),
                weather_observation_epoch=float(obs_t),
                forecast_wind_e_ms=float(pvec[0]), forecast_wind_n_ms=float(pvec[1]),
                truth_wind_e_ms=float(tvec[0]), truth_wind_n_ms=float(tvec[1]),
                wind_error_e_ms=float(tvec[0]-pvec[0]), wind_error_n_ms=float(tvec[1]-pvec[1]),
                forecast_wind_speed_ms=pspd, truth_wind_speed_ms=tspd,
                wind_speed_error_ms=float(tspd-pspd),
                forecast_Hs_m=phs, truth_Hs_m=ths, hs_error_m=float(ths-phs),
                predictor=WEATHER_PREDICTOR, predictor_contract=WEATHER_PREDICTOR_CONTRACT,
                timestamp_epoch_contract=WEATHER_TIMESTAMP_EPOCH_CONTRACT, truth_contract=WEATHER_TRUTH_CONTRACT,
                weather_data_contract=WEATHER_DATA_CONTRACT, moments_source="train",
                sample_overlap_policy="weather_timeline_global_nonoverlap", valid_for_formal=True,
            ))
            last_t1 = t1
            st["output"] += 1
        stats[str(int(h) if h.is_integer() else h)] = st
    return pd.DataFrame(rows), stats


def _sample_moments(train: pd.DataFrame, raw_counts: dict | None = None) -> pd.DataFrame:
    rows = []
    for h, g in train.groupby("h_min", sort=True):
        w = g[["wind_error_e_ms", "wind_error_n_ms"]].to_numpy(float)
        sp = g["wind_speed_error_ms"].to_numpy(float)
        hs = g["hs_error_m"].to_numpy(float)
        if len(g) < 2:
            raise ValueError(f"weather h={h} has fewer than 2 global train residuals")
        # Strong audit invariant: formal weather-moment intervals are globally non-overlapping.
        gg = g.sort_values("t0_epoch")
        starts = gg["t0_epoch"].to_numpy(float); ends = gg["t1_epoch"].to_numpy(float)
        if len(starts) > 1 and bool(np.any(starts[1:] < ends[:-1])):
            raise ValueError(f"weather h={h} train residuals overlap")
        mu = np.mean(w, axis=0)
        cov = np.asarray(np.cov(w.T, ddof=1), float)
        cov = 0.5 * (cov + cov.T)
        vals, vecs = np.linalg.eigh(cov)
        vals = np.maximum(vals, 0.0)
        cov = (vecs * vals) @ vecs.T
        cov = _binary64_psd_fix2(cov)
        key = str(int(float(h)) if float(h).is_integer() else float(h))
        n_raw = int((raw_counts or {}).get(key, {}).get("candidate", len(g)))
        rows.append(dict(
            h_min=float(h), n=int(len(g)), n_raw=n_raw,
            wind_bias_e_ms=float(mu[0]), wind_bias_n_ms=float(mu[1]),
            wind_sigma_ee=float(cov[0,0]), wind_sigma_en=float(cov[0,1]),
            wind_sigma_nn=float(cov[1,1]),
            wind_speed_bias_ms=float(np.mean(sp)), wind_speed_std_ms=float(np.std(sp, ddof=1)),
            hs_bias_m=float(np.mean(hs)), hs_std_m=float(np.std(hs, ddof=1)),
            predictor=WEATHER_PREDICTOR, predictor_contract=WEATHER_PREDICTOR_CONTRACT,
            timestamp_epoch_contract=WEATHER_TIMESTAMP_EPOCH_CONTRACT, truth_contract=WEATHER_TRUTH_CONTRACT,
            weather_data_contract=WEATHER_DATA_CONTRACT,
            moments_source="train", sample_overlap_policy="weather_timeline_global_nonoverlap",
            purge_min=float(g["purge_min"].min()), valid_for_formal=True,
            t0_min_epoch=float(g["t0_epoch"].min()), t0_max_epoch=float(g["t0_epoch"].max()),
        ))
    return pd.DataFrame(rows)


def _write_json(mom: pd.DataFrame, path: Path, source_files: dict):
    payload = {
        "weather_data_contract": WEATHER_DATA_CONTRACT,
        "predictor": WEATHER_PREDICTOR,
        "predictor_contract": WEATHER_PREDICTOR_CONTRACT,
        "timestamp_epoch_contract": WEATHER_TIMESTAMP_EPOCH_CONTRACT,
        "truth_contract": WEATHER_TRUTH_CONTRACT,
        "source_files": source_files,
        "cells": mom.to_dict(orient="records"),
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")



def _generate_weather_products(weather_csv: Path, xi_train_path: Path,
                               xi_validation_path: Path, xi_test_path: Path,
                               out_dir: Path, max_weather_gap_min: float = 90.0) -> dict:
    """Generate formal weather residual products from the just-written Xi splits.

    This is intentionally part of step7 so Xi and weather residuals share the exact
    same split/purge provenance.  Forecasts use only weather records at or before
    t0; future ERA5/CMEMS values are truth only.
    """
    weather_csv = Path(weather_csv)
    if not weather_csv.is_file():
        raise FileNotFoundError(weather_csv)
    if not (math.isfinite(float(max_weather_gap_min)) and float(max_weather_gap_min) > 0.0):
        raise ValueError("--max-weather-gap-min must be finite and >0")
    for p in (xi_train_path, xi_validation_path, xi_test_path):
        if not Path(p).is_file():
            raise FileNotFoundError(p)
    _, times, wvec, wspd, hs = _load_weather(weather_csv)
    xi_train = _validate_xi_split(Path(xi_train_path), "train")
    xi_val = _validate_xi_split(Path(xi_validation_path), "validation")
    xi_test = _validate_xi_split(Path(xi_test_path), "test")
    max_gap_s = 60.0 * float(max_weather_gap_min)
    src = {
        "weather_csv": {"path": str(weather_csv.resolve()), "sha256": _sha256(weather_csv)},
        "xi_train": {"path": str(Path(xi_train_path).resolve()), "sha256": _sha256(Path(xi_train_path))},
        "xi_validation": {"path": str(Path(xi_validation_path).resolve()), "sha256": _sha256(Path(xi_validation_path))},
        "xi_test": {"path": str(Path(xi_test_path).resolve()), "sha256": _sha256(Path(xi_test_path))},
    }
    outputs = {}
    drop_report = {}
    for name, frame in (("train", xi_train), ("validation", xi_val), ("test", xi_test)):
        enriched, dropped = _make_residuals(
            frame, times, wvec, wspd, hs, max_gap_s,
            src["weather_csv"]["sha256"], src["xi_train"]["sha256"])
        if enriched.empty:
            raise RuntimeError(
                f"{name}: no weather residual rows could be constructed; "
                f"weather_epoch_range=[{times[0]:.0f},{times[-1]:.0f}], "
                f"xi_t0_range=[{float(frame['t0_epoch'].min()):.0f},{float(frame['t0_epoch'].max()):.0f}], "
                f"dropped={dropped}")
        out_name = {
            "train": "xi_weather_samples_caseB.csv",
            "validation": "xi_weather_samples_validation_caseB.csv",
            "test": "xi_weather_samples_test_caseB.csv",
        }[name]
        out_path = out_dir / out_name
        enriched.to_csv(out_path, index=False, encoding="utf-8-sig")
        outputs[name] = (enriched, out_path)
        drop_report[name] = {**dropped, "input": int(len(frame)), "output": int(len(enriched))}
        log.info("天气残差 %s: %d -> %d; dropped=%s", name, len(frame), len(enriched), dropped)
    # Weather moments are calibrated on the weather timeline itself, not on AIS/ship row density.
    # Use a globally safe train window ending at the earliest validation launch time across ships.
    horizons = sorted(set(float(x) for x in xi_train["h_min"]))
    train_start_epoch = float(xi_train["t0_epoch"].min())
    train_end_epoch = float(xi_val["t0_epoch"].min())
    purge_min = float(xi_train["purge_min"].min())
    timeline_train, timeline_stats = _make_weather_timeline_train_residuals(
        times, wvec, wspd, hs, horizons, train_start_epoch, train_end_epoch,
        purge_min, max_gap_s)
    if timeline_train.empty:
        raise RuntimeError("no globally non-overlapping weather timeline train residuals could be constructed")
    got_h = {float(x).hex() for x in timeline_train["h_min"]}
    want_h = {float(x).hex() for x in horizons}
    if got_h != want_h:
        raise RuntimeError(f"weather timeline train horizon support incomplete: want={horizons}, got={sorted(set(timeline_train['h_min']))}")
    timeline_path = out_dir / "weather_residual_samples_caseB.csv"
    timeline_train.to_csv(timeline_path, index=False, encoding="utf-8-sig")
    moments = _sample_moments(timeline_train, timeline_stats)
    moments["weather_source_sha256"] = src["weather_csv"]["sha256"]
    moments["xi_train_source_sha256"] = src["xi_train"]["sha256"]
    m_csv = out_dir / "weather_moments_caseB.csv"
    m_json = out_dir / "weather_moments_caseB.json"
    moments.to_csv(m_csv, index=False, encoding="utf-8-sig")
    _write_json(moments, m_json, src)
    report = out_dir / "_weather_residual_report.txt"
    lines = [
        "==== formal no-leak weather residual report ====",
        f"predictor={WEATHER_PREDICTOR}",
        f"predictor_contract={WEATHER_PREDICTOR_CONTRACT}",
        f"timestamp_epoch_contract={WEATHER_TIMESTAMP_EPOCH_CONTRACT}",
        f"truth_contract={WEATHER_TRUTH_CONTRACT}",
        f"weather_data_contract={WEATHER_DATA_CONTRACT}",
        f"weather_csv={weather_csv.resolve()}",
        f"weather_sha256={src['weather_csv']['sha256']}",
        f"horizons={moments['h_min'].tolist()}",
        "moments_source=train",
        "sample_overlap_policy=weather_timeline_global_nonoverlap",
        f"weather_train_window_epoch=[{train_start_epoch:.0f},{train_end_epoch:.0f})",
        f"weather_timeline_stats={json.dumps(timeline_stats, ensure_ascii=False)}",
        f"weather_timeline_samples={timeline_path.name}",
        "joint_holdout_policy=Xi-timestamps-for-real-replay-only; not used to estimate WeatherAmbiguity",
        "synthetic_weather=False",
        "operational_forecast_archive=False",
        "interpretation=real historical out-of-sample residuals of the declared no-leak predictor against ERA5/CMEMS truth proxy",
        f"drop_report={json.dumps(drop_report, ensure_ascii=False)}",
        "", moments.to_string(index=False),
    ]
    report.write_text("\n".join(lines), encoding="utf-8")
    return {"moments_csv": m_csv, "moments_json": m_json, "report": report,
            "timeline_train_csv": timeline_path, "timeline_stats": timeline_stats,
            "drop_report": drop_report, "outputs": {k: v[1] for k, v in outputs.items()}}

def project_local(lat, lon, lat0, lon0):
    x = R_EARTH * np.radians(lon - lon0) * np.cos(np.radians(lat0))
    y = R_EARTH * np.radians(lat - lat0)
    return x, y


def resample_segments(df: pd.DataFrame, dt_s: float, seg_gap_s: float):
    """按时间缺口切段，且仅在连续段内重采样。"""
    if dt_s <= 0 or seg_gap_s <= 0:
        raise ValueError("dt_s 与 seg_gap_s 必须为正。")
    ts = pd.to_datetime(df["t"], errors="coerce", utc=True)
    t = to_epoch_seconds_utc(ts)
    lat0, lon0 = float(df["lat"].mean()), float(df["lon"].mean())
    x, y = project_local(df["lat"].to_numpy(), df["lon"].to_numpy(), lat0, lon0)
    gaps = np.where(np.diff(t) > seg_gap_s)[0]
    bounds = np.concatenate([[0], gaps + 1, [len(t)]])
    segs = []
    for segment_id in range(len(bounds) - 1):
        a, b = bounds[segment_id], bounds[segment_id + 1]
        if b - a < 3:
            continue
        raw_t = t[a:b]
        grid = np.arange(raw_t[0], raw_t[-1] + 1e-9, dt_s)
        if len(grid) < 3:
            continue
        gx = np.interp(grid, raw_t, x[a:b])
        gy = np.interp(grid, raw_t, y[a:b])
        segs.append(dict(segment_id=int(segment_id), grid=grid, x=gx, y=gy,
                         lat0=lat0, lon0=lon0))
    return segs, lat0, lon0


def classify_state(sp_t0, turn_rate_deg_min, disp_window_m,
                   low_kn, dp_kn, dp_disp_m, turn_thr):
    sp_kn = float(sp_t0) / KN
    if sp_kn < dp_kn and disp_window_m < dp_disp_m:
        return "动力定位"
    if sp_kn < low_kn:
        return "低速"
    if abs(turn_rate_deg_min) > turn_thr:
        return "转弯"
    return "直航"


def state_at_index(gx, gy, idx: int, vw: int, dt: float,
                   low_kn: float, dp_kn: float, dp_disp_m: float,
                   turn_thr: float):
    """Classify the realized vessel state at ``idx`` using observations up to ``idx``.

    This label is an audit target, not an optimization input.  It is therefore
    allowed to use the realized trajectory up to the recovery instant while
    preserving the same state thresholds used at launch.
    """
    if int(idx) < int(vw):
        raise ValueError("state_at_index requires idx >= vw")
    idx = int(idx); vw = int(vw); dt = float(dt)
    vx = (float(gx[idx]) - float(gx[idx - vw])) / (vw * dt)
    vy = (float(gy[idx]) - float(gy[idx - vw])) / (vw * dt)
    speed_ms = math.hypot(vx, vy)
    course0 = math.degrees(math.atan2(float(gy[idx]) - float(gy[idx - vw]),
                                      float(gx[idx]) - float(gx[idx - vw])))
    cw = max(1, vw // 2)
    if idx - vw - cw >= 0:
        course1 = math.degrees(math.atan2(
            float(gy[idx - cw]) - float(gy[idx - vw - cw]),
            float(gx[idx - cw]) - float(gx[idx - vw - cw])))
        dcourse = (course0 - course1 + 180.0) % 360.0 - 180.0
        turn_rate = dcourse / (cw * dt / 60.0)
    else:
        turn_rate = 0.0
    displacement = math.hypot(float(gx[idx]) - float(gx[idx - vw]),
                              float(gy[idx]) - float(gy[idx - vw]))
    state = classify_state(speed_ms, turn_rate, displacement,
                           low_kn, dp_kn, dp_disp_m, turn_thr)
    return dict(state=str(state), speed_ms=float(speed_ms),
                turn_rate_deg_min=float(turn_rate),
                displacement_window_m=float(displacement))


def purged_split_by_track(all_df: pd.DataFrame, fracs: list[float], purge_min: float):
    """对每条源轨迹分别进行时间切分，避免不同船/不同日期被全局分位数混切。"""
    train_parts, val_parts, test_parts, meta = [], [], [], []
    group_col = "source_track_id" if "source_track_id" in all_df.columns else "source_track"
    for source_track_id, g in all_df.groupby(group_col, sort=True):
        source_track = str(g["source_track"].iloc[0])
        starts = np.sort(g["t0_epoch"].astype(float).unique())
        if len(starts) < 3:
            raise ValueError(f"{source_track}: 可用起飞时刻不足，无法三段切分。")
        train_end = float(np.quantile(starts, fracs[0]))
        validation_end = float(np.quantile(starts, fracs[0] + fracs[1]))
        validation_start = train_end + 60.0 * purge_min
        test_start = validation_end + 60.0 * purge_min
        tr = g[g["t1_epoch"] <= train_end].copy()
        va = g[(g["t0_epoch"] >= validation_start) &
               (g["t1_epoch"] <= validation_end)].copy()
        te = g[g["t0_epoch"] >= test_start].copy()
        if tr.empty or va.empty or te.empty:
            raise ValueError(
                f"{source_track}: purged 切分后为空(train/val/test={len(tr)}/{len(va)}/{len(te)})；"
                "请增加轨迹跨度或调整 split/purge。")
        train_parts.append(tr); val_parts.append(va); test_parts.append(te)
        meta.append(dict(source_track=source_track, source_track_id=str(source_track_id),
                         train_end_epoch=train_end,
                         validation_start_epoch=validation_start,
                         validation_end_epoch=validation_end, test_start_epoch=test_start,
                         train_n=len(tr), validation_n=len(va), test_n=len(te)))
    return (pd.concat(train_parts, ignore_index=True),
            pd.concat(val_parts, ignore_index=True),
            pd.concat(test_parts, ignore_index=True), meta)


def thin_nonoverlap_samples(df: pd.DataFrame) -> pd.DataFrame:
    """按源轨迹、连续段和 horizon 选择不重叠预测区间。

    相邻 30 秒起点的 30 分钟预测误差共享 98% 以上的观测区间，不能把文件行数解释成
    独立样本量。该规则在每个 ``(track,segment,h)`` 内按时间贪心选择下一条
    ``t0 >= previous_t1`` 的样本；状态标签随被选起点保留，不跨状态伪造样本。
    """
    if df.empty:
        return df.copy()
    parts = []
    group_cols = [c for c in ("source_track_id", "segment_id", "h_min") if c in df.columns]
    if not group_cols:
        group_cols = ["mmsi", "h_min"]
    for _, g in df.sort_values("t0_epoch").groupby(group_cols, sort=False):
        keep = []
        last_end = -float("inf")
        for idx, row in g.iterrows():
            t0 = float(row["t0_epoch"]); t1 = float(row["t1_epoch"])
            if t0 >= last_end:
                keep.append(idx); last_end = t1
        if keep:
            parts.append(g.loc[keep])
    return pd.concat(parts, ignore_index=True) if parts else df.iloc[0:0].copy()


def _psd_cov(arr: np.ndarray) -> np.ndarray:
    """Return a symmetric 2x2 covariance that is PSD as exact binary64 reals.

    ``eigh`` projection is mathematically PSD but its reconstruction can land a
    few ulps outside the 2x2 PSD cone.  Formal CSVs are consumed as exact
    binary64 finite-model inputs, so finish by shrinking only the off-diagonal
    entry toward zero until the exact rational determinant is nonnegative.
    """
    if len(arr) <= 1:
        return np.zeros((2, 2), float)
    cov = np.asarray(np.cov(arr.T, ddof=1), float)
    cov = 0.5 * (cov + cov.T)
    vals, vecs = np.linalg.eigh(cov)
    vals = np.maximum(vals, 0.0)
    cov = (vecs * vals) @ vecs.T
    cov = 0.5 * (cov + cov.T)
    a = max(float(cov[0, 0]), 0.0)
    c = max(float(cov[1, 1]), 0.0)
    b = float(cov[0, 1])
    if a == 0.0 or c == 0.0:
        b = 0.0
    else:
        target = Fraction.from_float(a) * Fraction.from_float(c)
        # Projection overshoot is normally only a handful of ulps.  The loop is
        # exact and monotone, so it cannot enlarge covariance correlation.
        while Fraction.from_float(b) * Fraction.from_float(b) > target:
            b = math.nextafter(b, 0.0)
    return np.array([[a, b], [b, c]], dtype=float)


def _summary_row(mmsi: str, h: int, state: str, raw: pd.DataFrame,
                 used: pd.DataFrame, source_states: tuple[str, ...], rule: str,
                 min_cell_n: int, moments_source: str, merge_policy: str,
                 overlap_policy: str, purge_min: float | None = None,
                 max_horizon_min: float | None = None) -> dict:
    arr = used[["xi_e_m", "xi_n_m"]].to_numpy(float)
    mu = arr.mean(axis=0)
    cov = _psd_cov(arr)
    norms = np.hypot(arr[:, 0], arr[:, 1])
    mad = np.median(np.abs(arr - np.median(arr, axis=0)), axis=0)
    t0_min = pd.to_datetime(float(used["t0_epoch"].min()), unit="s", utc=True).isoformat()
    t0_max = pd.to_datetime(float(used["t0_epoch"].max()), unit="s", utc=True).isoformat()
    state_change_rate = float("nan")
    recovery_mode = "unknown"
    if {"actual_recovery_state", "c_state"}.issubset(used.columns):
        launch_states = used["c_state"].astype(str)
        recovery_states = used["actual_recovery_state"].astype(str)
        state_change_rate = float((launch_states != recovery_states).mean())
        modes = recovery_states.mode()
        recovery_mode = str(modes.iloc[0]) if not modes.empty else "unknown"
    launch_speed_p50 = (float(pd.to_numeric(used["launch_speed_ms"], errors="coerce").median())
                        if "launch_speed_ms" in used.columns else float("nan"))
    launch_speed_p95 = (float(pd.to_numeric(used["launch_speed_ms"], errors="coerce").quantile(0.95))
                        if "launch_speed_ms" in used.columns else float("nan"))
    return {
        "mmsi": mmsi, "h_min": int(h), "c_state": state,
        "n": int(len(arr)), "n_effective": int(len(arr)), "n_raw_state": int(len(raw)),
        "mu_e_m": round(float(mu[0]), 2), "mu_n_m": round(float(mu[1]), 2),
        # Covariance entries are mathematical model inputs.  Keep their binary64
        # values instead of presentation-rounding to 0.1, which can turn a PSD
        # sample covariance into an indefinite matrix after CSV serialization.
        "sigma_ee": float(cov[0, 0]),
        "sigma_en": float(cov[0, 1]),
        "sigma_nn": float(cov[1, 1]),
        "rms_norm_m": round(float(np.sqrt(np.mean(norms ** 2))), 2),
        "p50_norm_m": round(float(np.percentile(norms, 50)), 2),
        "p95_norm_m": round(float(np.percentile(norms, 95)), 2),
        "max_norm_m": round(float(norms.max()), 2),
        "mad_e_m": round(float(mad[0]), 2), "mad_n_m": round(float(mad[1]), 2),
        "launch_to_recovery_state_change_rate": state_change_rate,
        "actual_recovery_state_mode": recovery_mode,
        "launch_speed_p50_ms": launch_speed_p50,
        "launch_speed_p95_ms": launch_speed_p95,
        "predictor": PREDICTOR_NAME, "predictor_contract": PREDICTOR_CONTRACT,
        "timestamp_epoch_contract": TIMESTAMP_EPOCH_CONTRACT,
        "moments_source": moments_source, "sample_overlap_policy": str(overlap_policy),
        "purge_min": (float(purge_min) if purge_min is not None else float("nan")),
        "max_horizon_min": (float(max_horizon_min) if max_horizon_min is not None else float("nan")),
        "sample_rule": rule, "source_states": "+".join(source_states),
        "state_merge_policy": merge_policy, "min_cell_n": int(min_cell_n),
        "valid_for_formal": bool(
            moments_source == "train"
            and str(overlap_policy) == "nonoverlap"
            and purge_min is not None
            and max_horizon_min is not None
            and float(purge_min) >= float(max_horizon_min)
        ),
        "t0_min_iso": t0_min, "t0_max_iso": t0_max,
    }


def summarize_with_contract(d: pd.DataFrame, min_cell_n: int,
                            merge_policy: str, moments_source: str,
                            overlap_policy: str = "legacy-unspecified",
                            purge_min: float | None = None):
    """返回正式有效矩格与拒绝记录。低速/DP 合并要求两个原状态均有样本。"""
    accepted, rejected = [], []
    max_horizon_min = float(pd.to_numeric(d["h_min"], errors="coerce").max())
    groups = [(str(m), sub) for m, sub in d.groupby(d["mmsi"].astype(str))]
    groups.append(("ALL", d))
    for mmsi, base in groups:
        for h in sorted(base["h_min"].astype(int).unique()):
            hbase = base[base["h_min"].astype(int) == int(h)]
            for state in STATES:
                raw = hbase[hbase["c_state"].astype(str) == state]
                used = raw
                source_states = (state,)
                rule = "raw_state"
                if len(raw) < min_cell_n:
                    if merge_policy == "low_speed_pair" and state in LOW_SPEED_PAIR:
                        counts = {s: int((hbase["c_state"].astype(str) == s).sum()) for s in LOW_SPEED_PAIR}
                        pooled = hbase[hbase["c_state"].astype(str).isin(LOW_SPEED_PAIR)]
                        if all(counts[s] > 0 for s in LOW_SPEED_PAIR) and len(pooled) >= min_cell_n:
                            used = pooled
                            source_states = LOW_SPEED_PAIR
                            rule = "merged_low_speed_pair"
                        else:
                            rejected.append(dict(mmsi=mmsi, h_min=int(h), c_state=state,
                                                 n_raw_state=int(len(raw)), n_after_merge=int(len(pooled)),
                                                 reason="insufficient_after_predeclared_merge",
                                                 source_states="+".join(LOW_SPEED_PAIR)))
                            continue
                    else:
                        rejected.append(dict(mmsi=mmsi, h_min=int(h), c_state=state,
                                             n_raw_state=int(len(raw)), n_after_merge=int(len(raw)),
                                             reason="insufficient_raw_state",
                                             source_states=state))
                        continue
                accepted.append(_summary_row(mmsi, int(h), state, raw, used,
                                             source_states, rule, min_cell_n,
                                             moments_source, merge_policy, overlap_policy, purge_min,
                                             max_horizon_min))
    return accepted, rejected


def main() -> int:
    ap = argparse.ArgumentParser(description="统计船位预测误差 ξ_{h,c} 的正式矩信息")
    ap.add_argument("--tracks", nargs="+", required=False, help="一个或多个 track_<mmsi>.csv；weather-only 模式可省略")
    ap.add_argument("--out-dir", type=Path, default=Path("./tracks"))
    ap.add_argument("--weather-csv", type=Path, default=None,
                    help="可选：真实 weather_<farm>.csv；提供后在同一步生成 no-leak weather residual/moments")
    ap.add_argument("--weather-only-existing-splits", action="store_true",
                    help="仅从已冻结的 Xi train/validation/test 重建 weather-derived 产物；不重算 AIS/Xi。")
    ap.add_argument("--xi-train-path", type=Path, default=None,
                    help="weather-only: 现有 xi_samples_caseB.csv；默认 <out-dir>/xi_samples_caseB.csv")
    ap.add_argument("--xi-validation-path", type=Path, default=None,
                    help="weather-only: 现有 xi_samples_validation_caseB.csv；默认 <out-dir>/xi_samples_validation_caseB.csv")
    ap.add_argument("--xi-test-path", type=Path, default=None,
                    help="weather-only: 现有 xi_samples_test_caseB.csv；默认 <out-dir>/xi_samples_test_caseB.csv")
    ap.add_argument("--max-weather-gap-min", type=float, default=90.0,
                    help="天气 truth/interpolation 允许的最大相邻历史天气间隔(min)，默认 90")
    ap.add_argument("--dt", type=float, default=30.0, help="连续段重采样步长(s)")
    ap.add_argument("--seg-gap-min", type=float, default=5.0, help="超过该缺口切断轨迹段")
    ap.add_argument("--vel-window-s", type=float, default=60.0, help="t0 后向速度估计窗(s)")
    ap.add_argument("--horizons", type=str,
                    default=",".join(map(str, DEFAULT_HORIZONS_MIN)),
                    help="预测时长(分钟)，默认 5,10,...,60")
    ap.add_argument("--low-kn", type=float, default=1.0)
    ap.add_argument("--dp-kn", type=float, default=0.3)
    ap.add_argument("--dp-disp-m", type=float, default=30.0)
    ap.add_argument("--turn-deg-min", type=float, default=6.0)
    ap.add_argument("--min-cell-n", type=int, default=30,
                    help="正式 (h,c) 格最小训练样本量")
    ap.add_argument("--state-merge-policy", choices=["none", "low_speed_pair"],
                    default="low_speed_pair",
                    help="仅允许预先声明的低速+动力定位合并；直航/转弯不合并")
    ap.add_argument("--dump-samples", action="store_true",
                    help="导出 purged train/validation/test ξ 样本")
    ap.add_argument("--split-fracs", default="0.60,0.20,0.20")
    ap.add_argument("--purge-min", type=float, default=None,
                    help="切分边界隔离分钟数；默认=max(horizons)")
    ap.add_argument("--moments-source", choices=["train", "all"], default="train",
                    help="正式默认 train；all 仅允许消融")
    ap.add_argument("--sample-overlap-policy", choices=["nonoverlap", "all"],
                    default="nonoverlap",
                    help="正式默认 nonoverlap：同一轨迹/段/h 的预测区间不重叠；all 仅作消融")
    args = ap.parse_args()

    if args.weather_only_existing_splits:
        if args.weather_csv is None or not Path(args.weather_csv).is_file():
            raise SystemExit("--weather-only-existing-splits 必须提供存在的 --weather-csv。")
        train_path = (Path(args.xi_train_path) if args.xi_train_path is not None
                      else Path(args.out_dir) / "xi_samples_caseB.csv")
        val_path = (Path(args.xi_validation_path) if args.xi_validation_path is not None
                    else Path(args.out_dir) / "xi_samples_validation_caseB.csv")
        test_path = (Path(args.xi_test_path) if args.xi_test_path is not None
                     else Path(args.out_dir) / "xi_samples_test_caseB.csv")
        frozen = [train_path, val_path, test_path]
        if any(not q.is_file() for q in frozen):
            raise SystemExit(
                "weather-only 缺少 frozen Xi split: "
                + ", ".join(str(q) for q in frozen if not q.is_file()))
        before = {q.name: _sha256(q) for q in frozen}
        Path(args.out_dir).mkdir(parents=True, exist_ok=True)
        products = _generate_weather_products(
            Path(args.weather_csv), train_path, val_path, test_path,
            Path(args.out_dir), float(args.max_weather_gap_min))
        after = {q.name: _sha256(q) for q in frozen}
        if before != after:
            raise RuntimeError("weather-only 运行期间 frozen Xi split 哈希发生变化。")
        manifest = dict(
            contract="weather-only-regeneration-v17.1-coherent-speed-primary-v1",
            predictor=WEATHER_PREDICTOR,
            predictor_contract=WEATHER_PREDICTOR_CONTRACT,
            weather_data_contract=WEATHER_DATA_CONTRACT,
            frozen_xi_sha256=before,
            weather_source_sha256=_sha256(Path(args.weather_csv)),
            outputs={k: str(v) for k, v in products.get("outputs", {}).items()},
            moments_csv=str(products["moments_csv"]),
            timeline_train_csv=str(products["timeline_train_csv"]),
            drop_report=products["drop_report"],
            final_test_outcomes_consumed_for_selection=False)
        mf = Path(args.out_dir) / "_weather_regeneration_manifest.json"
        mf.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
        print("=" * 96)
        print("V17.1 WEATHER-ONLY REGENERATION COMPLETE")
        print(f"predictor={WEATHER_PREDICTOR}")
        print(f"predictor_contract={WEATHER_PREDICTOR_CONTRACT}")
        print("frozen Xi hashes unchanged=True")
        print(f"drop_report={json.dumps(products['drop_report'], ensure_ascii=False)}")
        print(f"manifest={mf.resolve()}")
        print("No final-test performance/outcome statistic was evaluated or printed.")
        print("=" * 96)
        return 0

    if not args.tracks:
        raise SystemExit("非 weather-only 模式必须提供至少一个 --tracks。")

    horizons = parse_horizons(args.horizons)
    if args.min_cell_n < 2:
        raise SystemExit("--min-cell-n 必须至少为 2。")
    fracs = [float(x) for x in str(args.split_fracs).split(",")]
    if len(fracs) != 3 or any(x <= 0 for x in fracs) or abs(sum(fracs) - 1.0) > 1e-8:
        raise SystemExit("--split-fracs 必须是和为 1 的三个正数。")
    if args.moments_source != "train":
        log.warning("moments-source=all 仅用于消融，不得形成正式无泄漏结论。")

    dt = float(args.dt)
    if dt <= 0:
        raise SystemExit("--dt 必须为正。")
    for h in horizons:
        steps = round(float(h) * 60.0 / dt)
        if abs(steps * dt - float(h) * 60.0) > 1e-7:
            raise SystemExit(
                f"--dt={dt:g}s 不能精确表示 h={h}min；正式统计要求 h·60/dt 为整数。")
    vw_float = float(args.vel_window_s) / dt
    if abs(round(vw_float) - vw_float) > 1e-7:
        raise SystemExit("--vel-window-s 必须是 --dt 的整数倍，避免预测器窗口口径漂移。")
    seg_gap_s = float(args.seg_gap_min) * 60.0
    vw = max(1, int(round(float(args.vel_window_s) / dt)))
    samples_full = []
    sample_id = 0

    for tp in args.tracks:
        path = Path(tp)
        source_track_id = str(path.expanduser().resolve())
        mmsi = path.stem.replace("track_", "")
        df = load_track(path)
        if df.empty:
            log.warning("%s 空，跳过。", path.name)
            continue
        log.info("%s: %d 点 | %s → %s", path.name, len(df), df["t"].min(), df["t"].max())
        segs, _lat0, _lon0 = resample_segments(df, dt, seg_gap_s)
        n_pairs = 0
        for seg in segs:
            gx, gy, grid = seg["x"], seg["y"], seg["grid"]
            n = len(gx)
            h_steps = {h: int(round(h * 60.0 / dt)) for h in horizons}
            for i in range(vw, n):
                vx = (gx[i] - gx[i - vw]) / (vw * dt)
                vy = (gy[i] - gy[i - vw]) / (vw * dt)
                sp_t0 = math.hypot(vx, vy)
                c0 = math.degrees(math.atan2(gy[i] - gy[i - vw], gx[i] - gx[i - vw]))
                cw = max(1, vw // 2)
                if i - vw - cw >= 0:
                    c1 = math.degrees(math.atan2(gy[i - cw] - gy[i - vw - cw],
                                                 gx[i - cw] - gx[i - vw - cw]))
                    dcourse = (c0 - c1 + 180.0) % 360.0 - 180.0
                    turn_rate = dcourse / (cw * dt / 60.0)
                else:
                    turn_rate = 0.0
                disp_win = math.hypot(gx[i] - gx[i - vw], gy[i] - gy[i - vw])
                state = classify_state(sp_t0, turn_rate, disp_win,
                                       args.low_kn, args.dp_kn, args.dp_disp_m,
                                       args.turn_deg_min)
                for h, hs in h_steps.items():
                    j = i + hs
                    if j >= n:
                        continue
                    px = gx[i] + vx * (hs * dt)
                    py = gy[i] + vy * (hs * dt)
                    actual = state_at_index(
                        gx, gy, j, vw, dt, args.low_kn, args.dp_kn,
                        args.dp_disp_m, args.turn_deg_min)
                    samples_full.append(dict(
                        sample_id=sample_id, mmsi=mmsi, source_track=path.name,
                        source_track_id=source_track_id,
                        segment_id=int(seg["segment_id"]), predictor=PREDICTOR_NAME,
                        h_min=int(h), c_state=state,
                        launch_speed_ms=float(sp_t0),
                        launch_turn_rate_deg_min=float(turn_rate),
                        launch_displacement_window_m=float(disp_win),
                        t0_epoch=float(grid[i]), t1_epoch=float(grid[j]),
                        xi_e_m=float(gx[j] - px), xi_n_m=float(gy[j] - py),
                        actual_recovery_state=actual["state"],
                        actual_recovery_speed_ms=actual["speed_ms"],
                        actual_recovery_turn_rate_deg_min=actual["turn_rate_deg_min"],
                        actual_recovery_displacement_window_m=actual["displacement_window_m"]))
                    sample_id += 1; n_pairs += 1
        log.info("  生成 (t0,h) 误差样本对: %d", n_pairs)

    all_df_raw = pd.DataFrame(samples_full)
    if all_df_raw.empty:
        raise SystemExit("没有生成任何 ξ 样本，请检查轨迹跨度、缺口和 horizons。")
    if args.sample_overlap_policy == "nonoverlap":
        all_df = thin_nonoverlap_samples(all_df_raw)
        log.info("ξ 非重叠抽样: raw=%d → effective=%d", len(all_df_raw), len(all_df))
    else:
        all_df = all_df_raw.copy()
        log.warning("sample-overlap-policy=all 仅用于消融；行数不能解释为独立样本量。")
    purge_min = float(args.purge_min) if args.purge_min is not None else float(max(horizons))
    try:
        train_df, validation_df, test_df, split_meta = purged_split_by_track(
            all_df, fracs, purge_min)
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc
    moment_df = train_df if args.moments_source == "train" else all_df
    accepted, rejected = summarize_with_contract(
        moment_df, int(args.min_cell_n), args.state_merge_policy, args.moments_source,
        args.sample_overlap_policy, purge_min)
    if not accepted:
        raise SystemExit("没有任何 (h,c) 格通过样本量门槛；请增加数据或调整预先声明的合并策略。")

    res = pd.DataFrame(accepted).sort_values(["mmsi", "h_min", "c_state"]).reset_index(drop=True)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    csv_path = args.out_dir / "xi_moments_caseB.csv"
    res.to_csv(csv_path, index=False, encoding="utf-8-sig")
    (args.out_dir / "xi_moments_caseB.json").write_text(
        json.dumps(accepted, ensure_ascii=False, indent=2), encoding="utf-8")

    effective_dump_samples = bool(args.dump_samples or args.weather_csv is not None)
    if args.weather_csv is not None and not args.dump_samples:
        log.info("提供 --weather-csv：自动导出 Xi train/validation/test 样本以绑定天气 provenance。")
    if effective_dump_samples:
        split_ids = {
            "train": set(train_df["sample_id"].astype(int)),
            "validation": set(validation_df["sample_id"].astype(int)),
            "test": set(test_df["sample_id"].astype(int)),
        }
        all_dump = all_df.copy()
        all_dump["split"] = "purged"
        for name, ids in split_ids.items():
            all_dump.loc[all_dump["sample_id"].isin(ids), "split"] = name
        outputs = {
            "xi_samples_caseB.csv": train_df.assign(split="train"),
            "xi_samples_validation_caseB.csv": validation_df.assign(split="validation"),
            "xi_samples_test_caseB.csv": test_df.assign(split="test"),
            "xi_samples_all_caseB.csv": all_dump,
        }
        for name, d in outputs.items():
            d = d.copy()
            d["predictor_contract"] = PREDICTOR_CONTRACT
            d["timestamp_epoch_contract"] = TIMESTAMP_EPOCH_CONTRACT
            d["sample_overlap_policy"] = str(args.sample_overlap_policy)
            d["purge_min"] = float(purge_min)
            d["moments_source"] = str(args.moments_source)
            d["valid_for_formal"] = bool(
                args.moments_source == "train"
                and args.sample_overlap_policy == "nonoverlap"
                and float(purge_min) >= float(max(horizons)))
            d["t0_iso"] = pd.to_datetime(d["t0_epoch"], unit="s", utc=True)
            d["t1_iso"] = pd.to_datetime(d["t1_epoch"], unit="s", utc=True)
            d.to_csv(args.out_dir / name, index=False, encoding="utf-8-sig")

    weather_products = None
    if args.weather_csv is not None:
        if not (args.moments_source == "train" and args.sample_overlap_policy == "nonoverlap"
                and float(purge_min) >= float(max(horizons))):
            raise SystemExit("--weather-csv 的 formal 天气链要求 moments-source=train、nonoverlap 且 purge>=max(horizons)。")
        weather_products = _generate_weather_products(
            Path(args.weather_csv),
            args.out_dir / "xi_samples_caseB.csv",
            args.out_dir / "xi_samples_validation_caseB.csv",
            args.out_dir / "xi_samples_test_caseB.csv",
            args.out_dir, float(args.max_weather_gap_min))

    lines = [
        "==== ξ_{h,c} 数据契约汇总 ====" ,
        f"预测器={PREDICTOR_NAME}; predictor_contract={PREDICTOR_CONTRACT}; timestamp_epoch_contract={TIMESTAMP_EPOCH_CONTRACT}",
        f"horizons(min)={horizons}; dt={dt:g}s; 段缺口={args.seg_gap_min:g}min",
        f"矩来源={args.moments_source}; min_cell_n={args.min_cell_n}; state_merge_policy={args.state_merge_policy}; overlap={args.sample_overlap_policy}",
        f"原始重叠样本={len(all_df_raw)}; 有效样本={len(all_df)}",
        f"purged split={fracs}; purge={purge_min:g}min; max_horizon={max(horizons):g}min; train/validation/test={len(train_df)}/{len(validation_df)}/{len(test_df)}",
        f"formal_purge_contract={bool(purge_min >= max(horizons))}",
        f"有效矩格={len(accepted)}; 拒绝格={len(rejected)}",
        "",
        "各源轨迹切分边界:",
    ]
    for m in split_meta:
        lines.append(
            f"  {m['source_track']}: train={m['train_n']} validation={m['validation_n']} test={m['test_n']} | "
            f"train_end={pd.to_datetime(m['train_end_epoch'], unit='s', utc=True).isoformat()} | "
            f"validation_start={pd.to_datetime(m['validation_start_epoch'], unit='s', utc=True).isoformat()} | "
            f"test_start={pd.to_datetime(m['test_start_epoch'], unit='s', utc=True).isoformat()}")
    pooled = res[res["mmsi"].astype(str) == "ALL"]
    if not pooled.empty:
        lines += ["", "ALL 有效格样本量:",
                  pooled.pivot_table(index="h_min", columns="c_state", values="n", fill_value=0).to_string()]
        if "launch_to_recovery_state_change_rate" in pooled.columns:
            lines += ["", "ALL 起飞状态→回收状态变化率(用于识别长 horizon 状态混合):",
                      pooled.pivot_table(index="h_min", columns="c_state",
                                         values="launch_to_recovery_state_change_rate",
                                         fill_value=0).round(3).to_string()]
        lines += ["", "ALL ξ p95 范数(m):",
                  pooled.pivot_table(index="h_min", columns="c_state",
                                     values="p95_norm_m", fill_value=0).round(1).to_string()]
    if rejected:
        lines += ["", "拒绝格（不会写入正式 xi_moments_caseB.csv）:"]
        for r in rejected:
            lines.append(
                f"  mmsi={r['mmsi']} h={r['h_min']} c={r['c_state']} raw={r['n_raw_state']} "
                f"after_merge={r['n_after_merge']} reason={r['reason']}")
    if weather_products is not None:
        lines += ["", "真实天气 no-leak 链:",
                  f"  weather_moments={weather_products['moments_csv'].name}",
                  f"  weather_report={weather_products['report'].name}",
                  f"  drop_report={json.dumps(weather_products['drop_report'], ensure_ascii=False)}"]
    report = "\n".join(lines)
    (args.out_dir / "_xi_report.txt").write_text(report, encoding="utf-8")
    print("\n" + report)
    formal_ok = bool(res["valid_for_formal"].astype(bool).all())
    label = "正式矩输出" if formal_ok else "机制/消融矩输出(valid_for_formal=False)"
    print(f"\n{label}: {csv_path.resolve()}")
    if not effective_dump_samples:
        print("提示: A+C 正式验证还需重新运行时显式加入 --dump-samples。")
    if weather_products is not None:
        print(f"正式天气矩输出: {weather_products['moments_csv'].resolve()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
